// Course directory — seeded from the "Golf Course Rating System via Lurch" sheet (both tabs).
const COURSE_DB = [
  {n:"Hogs Head",st:"Ireland"},
  {n:"Metedeconk National",st:"NJ"},
  {n:"Old Head",st:"Ireland"},
  {n:"Waterville",st:"Ireland"},
  {n:"Achusnet Golf Course",st:"MA"},
  {n:"Ak-Chin Southern Dunes",st:"AZ"},
  {n:"Aldarra Golf Club",st:"WA"},
  {n:"Allendale Country Club",st:"MA"},
  {n:"Anglebrook Golf Club",st:"NY"},
  {n:"Apawamis",st:"NY"},
  {n:"Apple Mountain",st:"CA"},
  {n:"Arcadia Bluffs Golf Club",st:"MI"},
  {n:"Architects Golf Club",st:"NJ"},
  {n:"Arrow Creek",st:"NV"},
  {n:"Atkinson Country Club",st:"NH"},
  {n:"Atlanta Athletic Club - Highlands",st:"GA"},
  {n:"Atlantic CIty Golf Club",st:"NJ"},
  {n:"Atlantic Golf Club",st:"NY"},
  {n:"Baiting Hollow Golf Club",st:"NY"},
  {n:"Balcomie Links - Crail Golfing Society",st:"Scotland"},
  {n:"Ballamor",st:"NJ"},
  {n:"Ballyowen",st:"NJ"},
  {n:"Baltusrol Golf Club",st:"NJ"},
  {n:"Barnbougle - Then Dunes",st:"Australia"},
  {n:"Barnbougle- The Lost Farm",st:"Australia"},
  {n:"Bayberry Hills Golf Course",st:"MA"},
  {n:"Beacon Hill Country Club",st:"NJ"},
  {n:"Bear Creek - West Course",st:"TX"},
  {n:"Beaver Meadow",st:"NH"},
  {n:"Bel Air Country Club",st:"CA"},
  {n:"Bethpage Black",st:"NY"},
  {n:"Birdsfoot Golf Course",st:"PA"},
  {n:"Blackstone golf club",st:"IL"},
  {n:"Blackstone National",st:"MA"},
  {n:"Blackwolf Run",st:"WI"},
  {n:"Blind Brook Golf Club",st:"CT"},
  {n:"Bluff Point Golf Resort",st:"NY"},
  {n:"Boilermaker Course",st:"IN"},
  {n:"Boyne Highlands - Arthur Hills Course",st:"MI"},
  {n:"Brabazon",st:"United Kingdom"},
  {n:"Brickyard Golf Club",st:"GA"},
  {n:"Cabot Cliffs",st:"Canada"},
  {n:"Cabot Links",st:"Canada"},
  {n:"Caledonia",st:"SC"},
  {n:"Callippe",st:"CA"},
  {n:"Canaan Valley",st:"WV"},
  {n:"Cantebury Woods Golf Club",st:"NH"},
  {n:"Cassique",st:"SC"},
  {n:"Chambers Bay",st:"WA"},
  {n:"CHARIOT RUN",st:"IN"},
  {n:"Charleston Springs South",st:"NJ"},
  {n:"Chesapeake Golf Club",st:"VA"},
  {n:"Colonial Country Club",st:"TX"},
  {n:"Columbia Country Club",st:"MD"},
  {n:"Concord Country Club",st:"MA"},
  {n:"Contra Costa country club",st:"CA"},
  {n:"Corica Park",st:"CA"},
  {n:"Corica Park South Course",st:"CA"},
  {n:"Country Club of the Poconos",st:"PA"},
  {n:"Country Club of the South",st:"GA"},
  {n:"Cowboys Golf Club",st:"TX"},
  {n:"Coyote Moon",st:"CA"},
  {n:"Cruden Bay",st:"Scotland"},
  {n:"Cypresswood",st:"TX"},
  {n:"Dublin Ranch",st:"CA"},
  {n:"Due Process",st:"NJ"},
  {n:"Dunes West Golf and River Club",st:"SC"},
  {n:"Dutch Elm Golf Course",st:"ME"},
  {n:"Eagle Chase Golf Club",st:"NC"},
  {n:"Eagle Ridge",st:"NJ"},
  {n:"Edgewood Lake Tahoe",st:"NV"},
  {n:"Elie",st:"Scotland"},
  {n:"Elks Golf Course - Elkins",st:"WV"},
  {n:"Elmcrest Country Club",st:"IA"},
  {n:"Erin Hills",st:"WI"},
  {n:"Essex Country Club",st:"MA"},
  {n:"Exeter Golf Course",st:"RI"},
  {n:"Fairmont Saint Andrews",st:"Scotland"},
  {n:"Fenner Hill",st:"RI"},
  {n:"Fiddlers Elbow",st:"NJ"},
  {n:"Fishers Island",st:"NY"},
  {n:"Forsgate Country Club",st:"NJ"},
  {n:"Fort Monmouth / Suneagles Golf Course",st:"NJ"},
  {n:"Fossil Trace Golf Club",st:"CO"},
  {n:"Fox Hopyard",st:"CT"},
  {n:"Franklin Park",st:"MA"},
  {n:"Fresh Pond",st:"MA"},
  {n:"Friar's Head",st:"NY"},
  {n:"Garden City Country Club",st:"NY"},
  {n:"George Wright ( kinda forget but know i played)",st:"MA"},
  {n:"Glen Oaks Country Club",st:"NY"},
  {n:"Goose creek golf club",st:"CA"},
  {n:"Grande Dunes",st:"SC"},
  {n:"Granite Links",st:"MA"},
  {n:"Greathorse Golf Club",st:"MA"},
  {n:"Green Harbor Golf Course",st:"MA"},
  {n:"Green Meadow Golf Course",st:"NH"},
  {n:"Grindstone Neck Golf Course",st:"ME"},
  {n:"Gus Wortham Golf Course",st:"TX"},
  {n:"Harbor Shores Golf Course",st:"MI"},
  {n:"Heritage Bluffs Golf Club",st:"IL"},
  {n:"Heron Point",st:"SC"},
  {n:"Holly Ridge golf links",st:"NC"},
  {n:"Hominy Hill",st:"NJ"},
  {n:"Hopkington Country Club",st:"MA"},
  {n:"Indian Ridge Golf Club",st:"OH"},
  {n:"Iron Horse CC",st:"NE"},
  {n:"Jefferson District Golf course",st:"VA"},
  {n:"Keith Hills Country Club",st:"NC"},
  {n:"Keller Golf Course",st:"MN"},
  {n:"Kiawah Island Turtle Point",st:"SC"},
  {n:"Kinderlou Forest Golf Club",st:"GA"},
  {n:"Kingston Heath",st:"Scotland"},
  {n:"Kirkbrae Country Club",st:"RI"},
  {n:"Knickerbocker Country Club",st:"NJ"},
  {n:"La Quinta Resort Mountain Course",st:"CA"},
  {n:"La Tourette",st:"NY"},
  {n:"Lake Merced",st:"CA"},
  {n:"Lake Morey",st:"VT"},
  {n:"Lake of Isles - Public",st:"CT"},
  {n:"Las Positas Golf Course",st:"CA"},
  {n:"Legends - Heathland",st:"SC"},
  {n:"Leven Thistle",st:"Scotland"},
  {n:"Logan Country Club",st:"WV"},
  {n:"LuLu Country Club",st:"PA"},
  {n:"Makefield Highlands Golf Club",st:"PA"},
  {n:"Mammoth Dunes",st:"WI"},
  {n:"Maplegate Country Club",st:"MA"},
  {n:"Meadow Golf Course - Peabody",st:"MA"},
  {n:"Meadow Wood Golf Course",st:"RI"},
  {n:"Meadowlands golf club",st:"NC"},
  {n:"Medinah",st:"IL"},
  {n:"Mercer Oaks Golf Course",st:"NJ"},
  {n:"Metropolitan",st:"CA"},
  {n:"Miami Shores Country Club",st:"FL"},
  {n:"Mid Ocean Club",st:"Bermuda"},
  {n:"Mid Pines",st:"NC"},
  {n:"Mif Albright at Corica Park",st:"CA"},
  {n:"Minnesota National",st:"MN"},
  {n:"Mirimichi",st:"TN"},
  {n:"Monarch Bay",st:"CA"},
  {n:"Monterey Peninsula Country Club",st:"CA"},
  {n:"Mossy Oak",st:"MS"},
  {n:"Mt. Hood Municipal",st:"MA"},
  {n:"Myopia Hunt Club",st:"MA"},
  {n:"Myrtlewood (Pinehills)",st:"SC"},
  {n:"Navesink Country Club",st:"NJ"},
  {n:"Newport National",st:"RI"},
  {n:"Newton Commonwealth",st:"MA"},
  {n:"Nonquitt Golf Course",st:"MA"},
  {n:"Oak Marsh at Amelia Island Plantation",st:"FL"},
  {n:"Oakbourne Country Club",st:"LA"},
  {n:"Oakmont Country Club",st:"PA"},
  {n:"Old Corkscrew",st:"FL"},
  {n:"Old Del Monte",st:"CA"},
  {n:"Old Greenwood",st:"CA"},
  {n:"Old Greenwood GC",st:"CA"},
  {n:"Old Kinderhook",st:"MO"},
  {n:"Old Orchard Golf Course",st:"NJ"},
  {n:"Olympia Fields (North)",st:"IL"},
  {n:"Olympia Fields (South)",st:"IL"},
  {n:"Ottercreek",st:"Ontario Canada"},
  {n:"Pacific Dunes",st:"OR"},
  {n:"Pacific Grove",st:"CA"},
  {n:"Palmetto Dunes",st:"SC"},
  {n:"Palouse Ridge Golf Course",st:"WA"},
  {n:"Pasatiempo",st:"CA"},
  {n:"Patriots Point",st:"SC"},
  {n:"Pebble Beach",st:"CA"},
  {n:"Pembroke Country Club",st:"MA"},
  {n:"Pequot Golf club",st:"CT"},
  {n:"Peterborough Milton",st:"United Kingdom"},
  {n:"PGA National",st:"United Kingdom"},
  {n:"Pilgrim's Run Golf Club",st:"MI"},
  {n:"Pine Dunes Resort and Golf Club",st:"TX"},
  {n:"Pine Meadows Country Club",st:"MA"},
  {n:"Pinehills Jones Course",st:"MA"},
  {n:"Pinehills Nicklaus Course",st:"MA"},
  {n:"Pinehurst \\#2",st:"NC"},
  {n:"Pinehurst \\#4",st:"NC"},
  {n:"Pinehurst \\#8",st:"NC"},
  {n:"Piping Rock",st:"NY"},
  {n:"Ponkapoag",st:"MA"},
  {n:"Poppy Hills",st:"CA"},
  {n:"Poppy Ridge",st:"CA"},
  {n:"Port Royal",st:"Bermuda"},
  {n:"Pound Ridge Golf Club",st:"NY"},
  {n:"Presidents Golf Course",st:"MA"},
  {n:"Presidio golf course",st:"CA"},
  {n:"Primland",st:"VA"},
  {n:"Quail Ridge Country Club",st:"MA"},
  {n:"Quail Valley",st:"FL"},
  {n:"Ralph Myhre Golf Course",st:"VT"},
  {n:"Rancho Canada - West",st:"CA"},
  {n:"Red Hawk - Lakes course",st:"NV"},
  {n:"Red Tail Golf Club",st:"MA"},
  {n:"Redhawk - Hills Course",st:"NV"},
  {n:"Richmond Country Club",st:"RI"},
  {n:"Riomar Golf Club",st:"FL"},
  {n:"River Club",st:"GA"},
  {n:"Rivertowne Country Club",st:"SC"},
  {n:"Rolling Hills Country Club",st:"CT"},
  {n:"Ross bridge",st:"AL"},
  {n:"Royal Dornoch",st:"Scotland"},
  {n:"RTJ of the shoals - Fighting Joe",st:"AL"},
  {n:"RTJ of the Shoals - Schoolmaster",st:"AL"},
  {n:"Rumson Country Club",st:"NJ"},
  {n:"Rutland Water",st:"United Kingdom"},
  {n:"Saint Andrews - New Course",st:"Scotland"},
  {n:"Saint Andrews - Old Course",st:"Scotland"},
  {n:"Sand Creek Station Golf Course",st:"KS"},
  {n:"Sand Valley",st:"WI"},
  {n:"Sandpiper",st:"CA"},
  {n:"Sandy Burr Golf Course",st:"MA"},
  {n:"Saratoga National",st:"NY"},
  {n:"Saratoga Spa",st:"NY"},
  {n:"Seaview Golf & Country Club",st:"Canada"},
  {n:"Shaker Ridge Country Club",st:"NY"},
  {n:"Shark River",st:"NJ"},
  {n:"Shore Acres (played a few holes and rain out)",st:"IL"},
  {n:"Silver Spring Country Club",st:"CT"},
  {n:"Silvermine Golf Club",st:"CT"},
  {n:"Sky Creek Ranch",st:"TX"},
  {n:"Skyway (NJ but NYC can have the land)",st:"NY"},
  {n:"Sleepy Hollow",st:"OH"},
  {n:"South Shore Country Club",st:"MA"},
  {n:"Spyglass Hill",st:"CA"},
  {n:"Stanford Golf Course",st:"CA"},
  {n:"Stonebridge Country Club",st:"NH"},
  {n:"Stonewall Golf Club",st:"VA"},
  {n:"Stonewall Orchard",st:"IL"},
  {n:"Stow Acres Golf Course",st:"MA"},
  {n:"Strawberry farms",st:"CA"},
  {n:"Streamsong Black",st:"FL"},
  {n:"Streamsong Blue",st:"FL"},
  {n:"Streamsong Par 3",st:"FL"},
  {n:"Streamsong Red",st:"FL"},
  {n:"Sugarloaf Golf Course",st:"ME"},
  {n:"Sweetens Cove Golf Club",st:"TN"},
  {n:"Tall Pines Players Club",st:"PA"},
  {n:"Tanglewood Manor Golf Club",st:"PA"},
  {n:"Texas Rangers Golf Club",st:"TX"},
  {n:"The Belfry PGA National, Birmingham",st:"United Kingdom"},
  {n:"The Bridges",st:"CA"},
  {n:"The Course at Wente Vineyards",st:"CA"},
  {n:"The Cradle ( Pinehurst Par 3)",st:"NC"},
  {n:"The Dormie Club",st:"NC"},
  {n:"The Dunes Golf Links",st:"Australia"},
  {n:"The Fortress",st:"MI"},
  {n:"The Golf Club at Stonebridge",st:"LA"},
  {n:"The links at lighthouse sound",st:"MD"},
  {n:"The Links at Spanish Bay",st:"CA"},
  {n:"The Orchards Golf Club",st:"MI"},
  {n:"The Sandbox(Par 3)",st:"WI"},
  {n:"The Standard Club",st:"GA"},
  {n:"The Tribute Golf Links",st:"TX"},
  {n:"The Wilderness Golf Course",st:"TX"},
  {n:"Thornblade Country Club",st:"SC"},
  {n:"Tidewater",st:"SC"},
  {n:"Tierra de Sol",st:"Aruba"},
  {n:"Tobacco Road",st:"NC"},
  {n:"Torrey Pines South Course",st:"CA"},
  {n:"Tour 18",st:"TX"},
  {n:"TPC COLORADO",st:"CO"},
  {n:"TPC Harding Park",st:"CA"},
  {n:"TPC Sawgrass Stadium",st:"FL"},
  {n:"TPC Scottsdale Stadium Course",st:"AZ"},
  {n:"TPC Stonebrae",st:"CA"},
  {n:"True Blue",st:"SC"},
  {n:"Trump Links at Ferry Point",st:"NY"},
  {n:"Turtle Bay Golf",st:"HI"},
  {n:"Turtle Hill Golf Club(Par 3)",st:"Bermuda"},
  {n:"Wachesaw Plantation",st:"SC"},
  {n:"Wannamoisett CC",st:"RI"},
  {n:"Waukewan Golf Course",st:"NH"},
  {n:"Wayland Country Club",st:"MA"},
  {n:"Whaling City",st:"MA"},
  {n:"Whistling Straits",st:"WI"},
  {n:"Widow's Walk",st:"MA"},
  {n:"Wild Dunes - Harbor Course",st:"SC"},
  {n:"Wild Dunes - Links Course",st:"SC"},
  {n:"Willbrook Plantation",st:"SC"},
  {n:"Wilmington municipal golf course (Donald Ross)",st:"NC"},
  {n:"Windsong Farm",st:"MN"},
  {n:"Winged Foot - East Course",st:"NY"},
  {n:"Wintonbury Golf Course",st:"CT"},
  {n:"Woburn Country Club",st:"MA"},
  {n:"Wolfdancer at Hyatt Lost Pines",st:"TX"},
  {n:"Wollaston Golf Club",st:"MA"},
  {n:"Woodstone Country Club",st:"PA"},
  {n:"World Tour",st:"SC"}
];
