// Caddie HQ lesson library.
// Tags connect lessons to logged struggles; the Coach ranks by tag match.
// Struggle tags: short-putts, three-putts, tempo, early-lift, bunkers, off-tee,
// approach, chipping, mental, wedge-distance, equipment
const LESSONS = [
  // ---------- PUTTING ----------
  { id:'p1', shelf:'Putting', title:'Lag putting is a ladder, not a line', min:4,
    tags:['three-putts'],
    body:'Three-putts almost never come from bad reads — they come from bad speed. From 30+ feet, stop aiming at the hole and start aiming at a 6-foot circle around it. Any putt that dies inside that circle is a success, because you make nearly everything from 3 feet and roughly half from 6. Great lag putters think "roll it into the living room," not "make it."',
    drill:'Ladder drill: balls at 20, 30 and 40 ft. Two putts from each, working up and back down the ladder. Score a point for every ball that finishes inside 6 ft. 12 balls, target 9+.' },
  { id:'p2', shelf:'Putting', title:'The 2:1 tempo that ends "hit-y" putting', min:3,
    tags:['tempo','short-putts','three-putts'],
    body:'Your filmed stroke runs about 1:1 — backswing and through-stroke the same length and speed, which produces a short load and an accelerating stab. Tour tempo is close to 2:1: a backswing about twice as long as the down-stroke, with gravity doing the acceleration. When the backswing gets long enough, the hit disappears and distance control becomes automatic.',
    drill:'One-Two drill: count a steady "one" back, "two" through — same beat every rep. Better: a metronome at 70–76 bpm, one click at the top, one at impact. 20 reps before every practice green session.' },
  { id:'p3', shelf:'Putting', title:'Stay low past the tee', min:3,
    tags:['early-lift','short-putts'],
    body:'The single most consistent fault in your filmed sessions is the head popping up and out right after impact. Early lift changes loft and face direction at the worst moment and is a classic source of inconsistent roll. The fix-feel: the putter head chases the ball low to the ground, like you are sweeping dust toward the hole, and your eyes stay down until the ball is gone.',
    drill:'Gate + chase: place a tee 6 inches ahead of the ball on the line. After impact, the putter head must pass over the tee while staying below shin height. 15 reps, every session. This also quiets the toe-over release.' },
  { id:'p4', shelf:'Putting', title:'A short-putt routine you can trust under pressure', min:4,
    tags:['short-putts','mental'],
    body:'Misses from 5 feet compound when there is no routine — every putt becomes a new invention. Build a fixed 4-step sequence: (1) read from behind the ball, pick a spot 2 inches ahead on the line; (2) one rehearsal stroke looking at the hole, feeling the distance; (3) set the face behind the ball aimed at your spot before you take your stance; (4) one look, then go — no second look. Same order, same timing, every putt from inside 8 feet.',
    drill:'10-ball 5-footer test with full routine on every ball. Track makes and miss direction in the Putting Lab — that number is the scoreboard for your whole putting project.' },
  { id:'p5', shelf:'Putting', title:'Read break on the pro side', min:3,
    tags:['three-putts','short-putts'],
    body:'Amateurs miss the vast majority of breaking putts on the low ("amateur") side — the ball dies below the hole. The high-side miss at least keeps the hole in play as the ball slows. Rule of thumb: whatever break you see, play a bit more of it, and match it with dying speed rather than ramming the break out of the putt. On short breakers, pick the spot on the lip where the ball enters and treat it as a straight putt to that spot.',
    drill:'Around-the-clock at 5 ft on a sloped hole: 8 ball positions in a circle. Note which positions you miss low — those are your read-bias putts.' },
  // ---------- WEDGES & SHORT GAME ----------
  { id:'w1', shelf:'Wedges & Short Game', title:'The clock system: three swings, nine numbers', min:5,
    tags:['wedge-distance','approach'],
    body:'Guessing at partial wedges is why you get stuck between clubs. Give each wedge three calibrated swings — feel them as a clock: hands to 9 o\'clock (half), 10:30 (three-quarter), and full. Three wedges × three swings = nine reliable carry numbers that cover everything from 45 to 110 yards. Fill the matrix in your Bag tab once at the range with 5 balls per swing, then trust it on the course.',
    drill:'Range session: 5 balls per swing length per wedge, note the average carry (ignore the best and worst). Enter the numbers in the wedge matrix. Re-check twice a season.' },
  { id:'w2', shelf:'Wedges & Short Game', title:'Bounce is your friend — especially yours', min:4,
    tags:['chipping','bunkers','equipment'],
    body:'Bounce is the sole angle that stops the leading edge digging. As a shallow sweeper you flirt with thin strikes when bounce sits too high — which is why your build runs mid bounce (10/10/8), not 12–14°. Around the greens, use the bounce: weight only slightly forward, hands level (not dramatically pressed), and let the sole slide under the ball. The blade only digs when hands get too far ahead and the leading edge is presented to the turf.',
    drill:'Brush drill: no ball, make chipping swings that brush the grass with the sole — listen for a "thump," not a scrape of the leading edge. Then hit 10 chips trying to reproduce that thump.' },
  { id:'w3', shelf:'Wedges & Short Game', title:'Chip vs. pitch: pick the boring one', min:3,
    tags:['chipping','approach'],
    body:'Default order around the green: putt if you can, chip-and-run if you can\'t putt, pitch only when you must carry something. A low runner with your 50° breaks less stuff than a floated 60° — more margin on strike, spin and landing spot. Save the 60° flop (your M-grind specialty) for short-sided lies where nothing else works. The best short-game players are the most boring ones.',
    drill:'One ball, three clubs: from the same greenside lie, play a 50° runner, a 56° standard, and a 60° pitch to the same pin. Note which finishes closest — nine times out of ten it\'s the lowest-lofted option that was available.' },
  { id:'w4', shelf:'Wedges & Short Game', title:'Distance control is landing-spot control', min:3,
    tags:['chipping','wedge-distance'],
    body:'Stop looking at the pin on chips — pick the exact spot where the ball should land, usually a few paces onto the green, and let the roll-out do the rest. Rough guide: a 50° runner rolls about 2× its carry, a 56° about 1×, a 60° about half. Land three different clubs on the same spot and you get three different finish distances — that\'s the whole short game in one sentence.',
    drill:'Towel drill: lay a towel 3 paces onto the green. 5 balls each with 50°, 56°, 60°, all landing on the towel. Watch how differently they finish.' },
  // ---------- COURSE MANAGEMENT ----------
  { id:'c1', shelf:'Course Management', title:'Tee shots: play to the fat side', min:4,
    tags:['off-tee'],
    body:'The driver question isn\'t "can I hit the fairway" — it\'s "where is the miss that ruins the hole." Before every tee shot, find the side where a miss is dead (water, OB, trees, bunkers you can\'t advance from) and aim so your normal shot pattern fits on the other side. An 8-handicap\'s dispersion is roughly 60 yards wide with driver; give that oval room. Sometimes that means 3-wood or hybrid — par is a fine score from the fairway.',
    drill:'Next round: on every tee, say the dead side out loud before choosing a club and target. Log how many penalty strokes you take off the tee vs. your average.' },
  { id:'c2', shelf:'Course Management', title:'Approach shots: the pin is a lie', min:4,
    tags:['approach'],
    body:'At 8–9 handicap, aiming at tucked pins is a leak. Your proximity from 150 yards is 45+ feet on average — an aim point at the pin near an edge puts half your shots in the bunker or rough. Aim at the fat of the green (usually center, adjusted a touch toward the pin) and take the extra club: amateurs miss short far more than long. Center of green, back-edge distance, every time — birdies still happen, doubles stop happening.',
    drill:'One round experiment: aim dead center of every green regardless of pin. Count greens hit and compare to your average.' },
  { id:'c3', shelf:'Course Management', title:'Lay up to a full number', min:3,
    tags:['approach','wedge-distance'],
    body:'When you can\'t reach a par 5 or must pitch out, don\'t just advance it — lay up to one of your calibrated wedge numbers (that\'s what the matrix is for). A full 95-yard 56° beats an awkward 60-yard half-something for most players. Know your favorite number and hit lay-ups to it on purpose.',
    drill:'Pick your money number (most players: full gap wedge). Next three rounds, every lay-up finishes at that number. Track proximity from it.' },
  { id:'c4', shelf:'Course Management', title:'Bogey is not an emergency', min:3,
    tags:['mental','off-tee'],
    body:'The difference between an 84 and a 79 usually isn\'t more birdies — it\'s fewer doubles. Doubles come from hero recoveries: the 3-wood from the trees, the flop over water from a tight lie. When you\'re in trouble, take the highest-percentage route back to the fairway and accept the bogey putt. Count doubles per round in your log — driving that number toward zero is the fastest handicap drop available.',
    drill:'Trouble rule for one month: from any recovery spot, choose the club and line you would bet $100 you can execute 9 times out of 10. Nothing fancier.' },
  // ---------- MENTAL GAME ----------
  { id:'m1', shelf:'Mental Game', title:'One target, one thought', min:3,
    tags:['mental','approach','off-tee'],
    body:'Standing over the ball with three swing thoughts is a guarantee of a steer. The routine that works: pick the smallest possible target (not "the fairway" — a branch, a window, a mower line), one rehearsal feeling the shot, then swing with only the target in mind. Mechanics belong on the range; targets belong on the course.',
    drill:'Range game: never hit two balls at the same target. Every ball gets a new small target and a full routine. 20 balls = 20 first swings.' },
  { id:'m2', shelf:'Mental Game', title:'The 10-yard reset', min:3,
    tags:['mental'],
    body:'After a bad hole, the next tee shot is the most dangerous swing of the day — you\'re still replaying the double. Give yourself a hard reset ritual: after holing out, you get 10 yards of walking to be angry. At the 10-yard mark, the hole is filed away and the only thing that exists is the next shot. Sounds silly; works because it gives frustration a container instead of pretending it isn\'t there.',
    drill:'Practice it on good holes too: 10 yards of review, then present-tense only. The ritual has to be automatic before it\'s needed.' },
  { id:'m3', shelf:'Mental Game', title:'Practice like it counts', min:3,
    tags:['mental','short-putts'],
    body:'Twenty casual 5-footers teach you less than five with consequences. Pressure is a skill you can rehearse: put a score on everything, make yourself finish drills with a made putt, restart streaks when you miss. The 10-ball test in your Putting Lab exists precisely for this — a number you can\'t talk your way out of.',
    drill:'Finish every practice session with "3 to leave": three straight 5-footers with your full routine. Miss one, start over. You\'re not allowed to leave until it\'s done.' },
  // ---------- BUNKER PLAY ----------
  { id:'b1', shelf:'Bunker Play', title:'Hit the sand, not the ball', min:4,
    tags:['bunkers'],
    body:'The standard splash shot never touches the ball — the club enters the sand about two inches behind it and the sand throws the ball out. Setup does most of the work: face slightly open before you grip, ball forward of center, weight favoring the front foot, and swing along your body line with commitment. Your 56° with 10° of bounce is built for exactly this — let the sole skid, don\'t dig the leading edge.',
    drill:'Line drill: draw a line in the practice bunker, no ball. Make swings that splash sand starting at the line. Then put balls two inches ahead of the line and keep hitting the line.' },
  { id:'b2', shelf:'Bunker Play', title:'Bunker distance is follow-through length', min:3,
    tags:['bunkers'],
    body:'Same splash, different finishes: a short follow-through throws the ball a few paces; a full high finish sends it 20+ yards. Keep the entry point and effort identical and control distance only with how far the club swings through. Deceleration is the one unforgivable sin in sand — always finish.',
    drill:'Three-flag drill: pick short, middle and long targets from the same bunker. 5 balls each, changing nothing but follow-through length.' },
  { id:'b3', shelf:'Bunker Play', title:'Plugged lies: close the face, dig, walk away', min:3,
    tags:['bunkers'],
    body:'A fried-egg or plugged lie reverses the normal rules: square or slightly closed face, ball back of center, and a steep chop into the sand right behind the ball. The ball comes out low with no spin and runs — plan for that roll-out and just get it on the green. Trying to splash a plugged ball with an open face is how bunkers eat a whole scorecard.',
    drill:'Step on three balls in the practice bunker and play them out. Learning the shot when it doesn\'t count removes the panic when it does.' },
  // ---------- EQUIPMENT KNOWLEDGE ----------
  { id:'e1', shelf:'Equipment Knowledge', title:'Why your putter fights your stroke', min:4,
    tags:['short-putts','equipment'],
    body:'Toe-hang putters (like your Phantom 7.5 and Newport 2) are balanced to swing on an arc — the face naturally opens and closes. Your overhead-confirmed stroke is straight-back-straight-through, which never re-squares that rotating face; the toe keeps closing and the ball starts left. Face-balanced and zero-torque putters hold the face square on their own, which is why the exchange matters more than any drill for the equipment half of your left miss.',
    drill:'At the demo: 10 balls from 5 ft with the 7.5, then 10 with a zero-torque model, full routine both. The miss-direction pattern — not feel — makes the decision.' },
  { id:'e2', shelf:'Equipment Knowledge', title:'Grooves die quietly', min:3,
    tags:['equipment','wedge-distance','chipping'],
    body:'Wedge grooves wear down through sand, range balls and dirt — and spin loss is gradual, so you never notice the day it happens. By roughly 75–100 rounds a wedge can lose a third of its spin: chips release farther, full shots fly a touch longer and stop less. That\'s why the app counts rounds per wedge. Clean grooves after every shot from sand, and expect to replace your most-used wedge (the 56°) every couple of seasons.',
    drill:'Fingernail test: drag a nail across the face — grooves it doesn\'t catch in are worn. Compare the 56° face center vs. its unworn heel.' },
  { id:'e3', shelf:'Equipment Knowledge', title:'Grips: the 40-round rule', min:3,
    tags:['equipment'],
    body:'Grips harden and glaze long before they look worn. A slick grip forces a tighter hold, which adds tension all the way up to the shoulders — a swing killer nobody blames on the grip. Rule of thumb: regrip every 40 rounds or once a season, whichever comes first. The app counts your rounds so the reminder shows up before your grip pressure does.',
    drill:'Tension check: at address, hold the club at 3-out-of-10 grip pressure. If it feels like the club could slip, the grips are done.' },
  { id:'e4', shelf:'Equipment Knowledge', title:'Loft gaps beat brand loyalty', min:3,
    tags:['equipment','wedge-distance'],
    body:'The bag should be built around carry gaps, not logos. Your setup runs 44° PW then 50/56/60 — a 6/6/4 spread that plays fine off a strong PW. The sign it needs work: repeatedly finding yourself between clubs at the same yardage. If your logs show that, the fix is a 4-wedge ladder (48/52/56/60) at the cost of a long iron. Let the data in your rounds decide, not the shop wall.',
    drill:'For two weeks, note every approach where you were "between clubs" and the yardage. Three or more at the same number = a real gap.' },
];
