// Caddie HQ lesson library.
//
// THIS FILE IS THE FROZEN BASELINE — treat it exactly like seed() in app.js.
// Live changes go through coach-feed.json (`lesson-update` / `lesson-add` /
// `lesson-remove`), NOT by editing a lesson here. Editing in place overwrites the text on
// Jack's phone with no trail and no history, which is how two lessons stayed stale for
// three weeks (one still named a putter returned Jul 20). app.js merges this baseline
// with the feed edits in lessons(); nothing reads LESSONS directly.
//
// Tags connect lessons to logged struggles; the Coach ranks by tag match.
// Struggle tags: short-putts, three-putts, tempo, early-lift, bunkers, off-tee,
// approach, chipping, mental, wedge-distance, equipment
const LESSONS = [
  // ---------- PUTTING ----------
  { id:'p1', shelf:'Putting', title:'Lag putting is a ladder, not a line', min:4,
    tags:['three-putts'],
    body:'Three-putts almost never come from bad reads — they come from bad speed. From 30+ feet, stop aiming at the hole and start aiming at a 6-foot circle around it. Any putt that dies inside that circle is a success, because you make nearly everything from 3 feet and roughly half from 6. Great lag putters think "roll it into the living room," not "make it."',
    drill:'Ladder drill: balls at 20, 30 and 40 ft. Two putts from each, working up and back down the ladder. Score a point for every ball that finishes inside 6 ft. 12 balls, target 9+.' },
  { id:'p2', shelf:'Putting', title:'Your tempo is already right — protect it', min:3,
    tags:['tempo','short-putts','three-putts'],
    body:'This one is CLOSED, and it is worth knowing why. Your stroke was running about 1:1 back in July — a short load and an accelerating stab. It now measures 2.0:1 on the LINK across seven of eight clips, against a 2:1 target. That is the ingredient most amateurs never get, and you have it. So tempo is no longer a thing to fix; it is a thing to hold still. The reason it matters that it stays constant: distance on this putter comes from stroke LENGTH at a FIXED tempo, so the moment tempo starts moving with distance, the power curve you are building on the ladder stops meaning anything. If you catch yourself hitting AT a long putt, that is tempo drifting, and it is the fault showing itself.',
    drill:'Not a fix, a check. Once a fortnight: metronome at 70–76 bpm, one click at the top, one at impact, 20 strokes at mixed lengths. Every length should take the SAME beat — only the size changes. Any length that needs a different beat is the one to watch on the ladder.' },
  { id:'p3', shelf:'Putting', title:'Stay low past the tee', min:3,
    tags:['early-lift','short-putts'],
    body:'This was the most consistent fault in your early filmed sessions — the head popping up and out right after impact, changing loft and face direction at the worst possible moment. It CLOSED on film on Jul 30 and has stayed closed, so this is maintenance rather than a repair. Keep the feel that fixed it: the putter head chases the ball low to the ground, like you are sweeping dust toward the hole, and your eyes stay down until the ball is gone. It is worth keeping on the shelf because early lift is the classic fault that comes back quietly under pressure, and a short putt is where you would find out.',
    drill:'Gate + chase: place a tee 6 inches ahead of the ball on the line. After impact, the putter head must pass over the tee while staying below shin height. 15 reps, every session. This also quiets the toe-over release.' },
  { id:'p4', shelf:'Putting', title:'Why the routine is the thing under pressure', min:3,
    tags:['short-putts','mental'],
    body:'Misses from 5 feet compound when there is no routine, because every putt becomes a new invention — and inventing is what you do NOT want to be doing when it matters. The mechanism is simple: a routine has a fixed length, so it gives a rushing mind nothing to shorten and a stalling mind nothing to stretch. Your own record says this is where the damage is. Two of the Wianno matches were still live at the finish and both were lost on short putts, and your failure shows up on short putts under pressure rather than on the practice green. YOUR routine is already written and locked, so do not build a second one here — it lives in the Putting Routine plan, and the whole point is that there is one of it. This lesson exists to say why it earns the time, not to give you a different version.',
    drill:'20-ball five-footer with the FULL routine on every ball, including the beat count and the trigger. Log makes and miss direction in the Putting Lab. Pass mark is 2 or fewer LEFT misses per 20 — that number is the scoreboard for the whole short-putt project.' },
  { id:'p5', shelf:'Putting', title:'Read break on the pro side', min:3,
    tags:['three-putts','short-putts'],
    body:'Amateurs miss the vast majority of breaking putts on the low ("amateur") side — the ball dies below the hole. The high-side miss at least keeps the hole in play as the ball slows. Rule of thumb: whatever break you see, play a bit more of it, and match it with dying speed rather than ramming the break out of the putt. On short breakers, pick the spot on the lip where the ball enters and treat it as a straight putt to that spot.',
    drill:'Around-the-clock at 5 ft on a sloped hole: 8 ball positions in a circle. Note which positions you miss low — those are your read-bias putts.' },
  // ---------- AT-HOME PUTTING ----------
  { id:'h1', shelf:'At-Home Putting', title:'The coin gate: kill the left miss on carpet', min:3,
    tags:['short-putts'],
    body:'Your left miss starts at the face — and on a zero-torque head, the face at impact is the face you AIMED, because the head does not twist on the way through. That is what makes this drill worth more than it looks: the gate is not testing your delivery, it is testing your aim, which is where the miss was reclassified to on Aug 10. Build it on any six feet of carpet: two coins just wider than the putter head at the ball, and a second pair one putter-length ahead, barely wider than the ball. If the ball clips the far gate\'s left coin, you aimed left — instant, honest feedback with no green needed. Set the face BARELY OPEN as you do on the course, since that is the aim picture being tested.',
    drill:'20 putts through both gates at a target (a coaster, a table leg) 6 ft away. Count clean passes. Under 15? Slow down and watch the face, not the ball. Log the number — it should climb week over week.' },
  { id:'h2', shelf:'At-Home Putting', title:'The yardstick: a start-line machine for $3', min:3,
    tags:['short-putts'],
    body:'A metal yardstick (or any straight ruler) is the cheapest putting lab there is. Ball on one end, roll it down the stick — if the ball falls off before the far end, the face was open or closed at impact. With your SBST stroke and the LINK holding the face for you, a ball that stays on the stick every time is proof the stroke and the putter are finally doing the same job. When it falls off left, you\'ve found the old habit trying to come back.',
    drill:'10 balls down the yardstick before work or after dinner. Streak scoring: count consecutive balls that hold the full length, restart on a fall-off. Beat yesterday\'s streak.' },
  { id:'h3', shelf:'At-Home Putting', title:'Putt along the baseboard', min:3,
    tags:['short-putts','tempo'],
    body:'An SBST stroke has a built-in home practice station: any wall. Set up with the putter head a half-inch from the baseboard and make strokes keeping the heel that same half-inch away, back and through. If the heel drifts into the wall going back, you\'re pulling inside; if it drifts away coming through, an arc-and-release is sneaking into a stroke that is meant to be straight. The wall doesn\'t flatter you, which is the point — and on a head built not to twist, a path that wanders is one of the few things left that can still move the ball off line.',
    drill:'15 slow-motion strokes brushing an even gap off the baseboard, then 10 at full speed, then 5 with a ball rolled at a target along the wall. Three minutes, every day you don\'t see a green.' },
  { id:'h4', shelf:'At-Home Putting', title:'Film yourself like the coach does', min:4,
    tags:['early-lift','short-putts'],
    body:'Every fault we\'ve found came off film — and your phone works exactly the same on the living-room carpet. Prop the phone at shin height, face-on, and hit five putts; then overhead (down the line from above, the angle that confirmed SBST) for five more. You\'re checking two things: does the head stay down through impact, and does the putter chase low past where the ball was? The early lift shows up on carpet just like it does on the green, and catching it on a Tuesday is cheaper than finding it on Saturday\'s scorecard.',
    drill:'Weekly: film 5 putts face-on and 5 overhead at home, watch them back once at half speed. One note per session ("head stayed down 4/5") — send the clips in and they\'ll go in the Putting Lab like any filmed session.' },
  { id:'h5', shelf:'At-Home Putting', title:'Tempo reps don\'t need a green', min:3,
    tags:['tempo'],
    body:'The 2:1 tempo we\'re building is pure rhythm, and rhythm trains better at home than at the course — no hole to get "hit-y" at. Metronome app at 72 bpm: start the backswing on one click, strike the ball on the next. The backswing should feel twice as long as the through-stroke, with gravity doing the acceleration. Ten minutes of clicks on carpet beats an hour of outcome-watching on the practice green, because there\'s no outcome to chase — just the beat.',
    drill:'Metronome at 72 bpm, no target, no hole: 20 strokes without a ball, then 20 with a ball rolled to nowhere in particular. Eyes on tempo only. If a stroke feels rushed, it was — restart the count of 20.' },
  { id:'h6', shelf:'At-Home Putting', title:'Calibrate feel with your eyes closed', min:3,
    tags:['three-putts','mental'],
    body:'Distance control is a feel skill, and feel is trained by prediction, not repetition. On carpet: pick a target across the room, putt, and call "long," "short," or "flush" with your eyes closed before you look. Being wrong is the workout — every miscall recalibrates the link between stroke length and roll-out. Carpet is faster or slower than your greens and that\'s fine; you\'re not learning a distance, you\'re learning to *know what you just did*, which is the skill that kills three-putts from 35 feet.',
    drill:'10 putts to a target 15+ ft away, eyes closed at impact, call each one before looking. Score your calls, not the putts: 8/10 correct calls is the target. Then move the target and do it again.' },
  { id:'h8', shelf:'At-Home Putting', title:'Train the pop stroke on carpet', min:4,
    tags:['short-putts','tempo'],
    body:'The short-putt stroke is short back and short through, run from the SHOULDERS with the wrists silent — and carpet is the right place to build it, because there is no hole to make it about the result. Two things to rehearse. FIRST, the size: a backstroke small enough that you could not possibly reach a long putt with it, and a finish that stops soon after the ball. SECOND, and this is the one that matters, that the stroke is still ACCELERATING when it stops. A short finish that accelerated and a short finish that quit look identical afterwards, so you cannot judge it by the finish — judge it by how far the ball runs. The one thing to watch for: the putter head PASSING YOUR HANDS. That is the wrist releasing, which is the half of the classic pop stroke you are deliberately not copying.',
    drill:'Put a target 5 ft away on carpet and a second marker 17 INCHES past it — that is the researched pace for a short putt, firm enough to hold its line through the trodden ring around a real hole. 20 balls: the win is finishing between the target and the far marker, not hitting the target. If balls keep dying short, the through-stroke is quitting rather than merely being short.' },
  { id:'h7', shelf:'At-Home Putting', title:'The 20-in-a-row game', min:3,
    tags:['short-putts','mental'],
    body:'Home practice fails when it\'s aimless rolling in front of the TV. Give it teeth: pick a tight target — a cup on its side, a coin, the leg of a chair — from 4 feet, and the session isn\'t over until you\'ve hit it 20 times in a row. Miss number 19 and you start over. That manufactured pressure is the closest thing to a must-make 5-footer you can build indoors, and it\'s the same muscle as "3 to leave" at the practice green — consequences turn reps into skill.',
    drill:'20 consecutive hits on a coin-sized target from 4 ft, full routine on the last five (they\'re the ones with real pressure). Track your longest streak in your notes — mark the streak day done when you finish.' },
  // ---------- AT-HOME SWING ----------
  // The WINNERSPIRIT Miracle 201 work. This used to be a standing plan in the Swing
  // lab; it moved here Aug 13 2026 because a training is drills-and-streak, which is
  // what a lesson already is — plans say what to do on the course, Coach trains it.
  { id:'sw1', shelf:'At-Home Swing', title:'The Miracle 201: how the tool talks to you', min:4,
    tags:['tempo','off-tee'],
    body:'The Miracle 201 is a weighted (~550g), whippy carbon/glass-fibre trainer with two feedback channels, and knowing both is what turns it from a heavy stick into a coach. THE CLICK: a slider fires an audible click at the point of maximum speed — WHERE you hear it tells you WHEN you released. THE SPEED DIAL: adjustable from roughly 15–50 m/s (about 34–111 mph), setting how much speed is needed to trigger the click. Turn it down for tempo work, up to demand real clubhead speed. The reason it suits you specifically: the shaft is heavy and flexible, so you physically cannot rush it. It forces you to load and wait, which is the exact medicine for a quick, across-the-line top.',
    drill:'Setup and safety, every session: about 8 ft clear all round and a high ceiling, never near people, lights or a TV. Normal conventional grip and your real posture — it only transfers if the setup matches. Warm up with 20–30 slow smooth swings before anything hard; at 550g it is heavier than your driver and a cold max swing is how you tweak a back. Add a few LEFT-handed swings each session to balance the body.' },
  { id:'sw2', shelf:'At-Home Swing', title:'One-handed reps — the reset that is already working', min:3,
    tags:['off-tee','tempo'],
    body:'Confirmed Jul 27 and still the most valuable thing you do with this tool: swinging the 201 ONE-HANDED, trail hand only, lands the "drop into the slot" feel. The heavy head on a single hand exaggerates the shallowing and lag you are chasing, and it makes an early cast impossible to miss — you simply cannot hold it together if you throw the release away. Lean on it rather than treating it as a warm-up curiosity. Start every session with a few slow one-handed reps before going two-handed, and reach for it any time the top feels across the line.',
    drill:'6–8 slow one-handed trail-arm swings to open every session, then repeat them inside Drill 1 before each two-handed set. Any session where the top feels across the line, go back to one-handed until the drop returns.' },
  { id:'sw3', shelf:'At-Home Swing', title:'Load and wait — the tempo drill that outranks the rest', min:4,
    tags:['tempo','off-tee'],
    body:'Dial LOW. Make smooth 3:1 swings and feel the shaft bend and lag behind your hands at the top. If you snatch from the top it flails and the click fires early and weak — the tool will not let you fake this one. Count "one-and… two": a long patient load back, an unhurried transition, then let it sling. This is the drill that rewires the "great at the top but quick coming down" pattern, which is your own description of the fault, so treat it as the core of the whole programme rather than one item on a list.',
    drill:'Warm in with the one-handed reps, then 2 sets of 10 two-handed, both directions, dial low. Every session without exception. If the click is firing early, the load was not patient enough — slow the transition, not the backswing.' },
  { id:'sw4', shelf:'At-Home Swing', title:'Make the click fire PAST the ball', min:3,
    tags:['off-tee','approach'],
    body:'This targets your exact complaint — losing it through contact. The goal is that the click cracks at the BOTTOM of the arc, at or just past your lead leg, never up in the downswing. An early click means casting: throwing the release away before impact, with all your speed spent above the ball. Keep the wrists hinged and let the head release LATE so the click fires down where the ball would be. The value here is that it is audible: you do not need a camera or an opinion, you need to listen.',
    drill:'3 sets of 8, listening every rep and adjusting until the click consistently lives at or after the bottom of the arc. Log whether the click is firing past the ball yet — that is the number worth tracking on this drill.' },
  { id:'sw5', shelf:'At-Home Swing', title:'Hips lead, head lags — the transition drill', min:3,
    tags:['off-tee'],
    body:'From the top, start down with the LOWER BODY: feel the lead hip clear back and up while the trainer head still lags behind. Because that head is heavy and slow to catch up, it exaggerates the hips-lead-hands sequence you are trying to build, and it punishes the opposite instantly — spin the shoulders or arms first and the click comes early and weak. That is the same fault as the over-the-top slice, so this drill and Fix 2 in the Swing Focus plan are aimed at one thing, not two.',
    drill:'2 sets of 8, run straight after the wall and trail-foot-back drills in your Swing Focus plan so the feel carries across while it is fresh.' },
  { id:'sw6', shelf:'At-Home Swing', title:'Kill the laid-off top', min:3,
    tags:['off-tee'],
    body:'A position drill, so there is no speed in it at all. Slow reps to a PAUSE at the top, feeling the trail elbow point down and stay IN FRONT of your trail-hip seam. The whippy shaft is what makes this worth doing with the trainer rather than a club: an across-the-line or laid-off top feels obviously stuck and off-plane on the 201, where a normal club hides it well enough that you would need film to catch it.',
    drill:'10 slow reps to a pause, no speed. Check in a mirror or on a phone on a tripod that the shaft points at the target line and not right of it.' },
  { id:'sw7', shelf:'At-Home Swing', title:'Speed sets — and the weekly plan that stops you grinding', min:4,
    tags:['off-tee','tempo'],
    body:'Dial UP, after a full warm-up: all-out swings for pure speed, where the click only fires if you genuinely accelerate through the bottom. This is nervous-system work, so quality beats quantity and it must never turn into cardio. It also has to stay off your tempo days — the two goals fight each other, and doing both in one session gets you neither. The week that works: 2–3 short sessions of 10–15 minutes, alternating a TEMPO day (the drills above, low dial) with a SPEED day (this one, high dial). Do not max out every time.',
    drill:'3 sets of 5 max-effort swings with full rest between sets, plus a few non-dominant-side swings. Benchmark: the highest dial setting you can consistently trigger — track it week over week and watch it climb. Pre-round, 15–20 easy swings as a dynamic warm-up and tempo primer.' },
  // ---------- GREEN READING ----------
  { id:'g1', shelf:'Green Reading', title:'Green speed: look, feel, test, trust', min:4,
    tags:['three-putts'],
    body:'Four clues stack into one speed read. (1) Grain — grass grows in a direction; putting into the grain is slower, down-grain is faster. (2) Shine — this is really a grain clue, not a green clue: the same surface looks shiny when you\'re looking down-grain (your putt runs faster) and dull when you\'re looking into it (slower). (3) Slope — downhill faster, uphill slower, and the steeper it is the bigger the effect; on quick greens slope dwarfs everything else. (4) Moisture — wet or morning-dew greens are slower; sun and wind dry them out and speed them up as the round goes on, so the 8am read is stale by the back nine. No clue stands alone: combine them, then confirm with a feel putt before you trust the number.',
    drill:'First 3 minutes on the practice green, every round: two long putts looking at the hole (not the ball) and call the finish spot out loud before it stops. That calibrates the day\'s speed better than ten mechanical reps.' },
  { id:'g2', shelf:'Green Reading', title:'Grain: the read under the read', min:4,
    tags:['three-putts','short-putts'],
    body:'Grain matters most exactly where your ball is slowest — the last few feet — so it hits short putts and die-speed lags hardest. Three ways to find it: the shine test (shiny = down-grain, dull = into it); the cup test (the ragged, browning edge of the hole is the side the grass grows toward — the ball breaks that way as it dies); and the ecology test (grain tends to grow toward water, drainage, and the setting sun). Down-grain putts are faster and break more; into-the-grain putts are slower and hold their line. On a slow-dying short putt, grain can beat slope.',
    drill:'On the practice green, putt the same flat 10-footer in both directions with the same stroke. The distance gap between the two finishes is the day\'s grain strength — remember it on the course.' },
  { id:'g3', shelf:'Green Reading', title:'Read with your feet, from the low side', min:3,
    tags:['three-putts'],
    body:'Eyes get fooled by mowing lines and surrounding terrain; feet don\'t. Start the read on the walk up — the big tilt of the green is easiest to see from 20 yards out. Behind the ball, get low for the line, then walk the low side of the putt (the side the ball breaks toward): break is far easier to see from below the hole than from above it. And all the way through, notice your feet — if one feels lower than the other, believe your feet over your eyes. When eyes and feet disagree, the feet are usually right.',
    drill:'For nine holes, guess the break with eyes closed standing mid-putt — feet only — before doing your normal read. Count how often the feet-read was right. Most players start trusting their feet by hole five.' },
  { id:'g4', shelf:'Green Reading', title:'Speed picks the line', min:3,
    tags:['three-putts','short-putts'],
    body:'There is no such thing as "the" break — a putt has a different correct line for every speed. Firm takes break out; dying speed doubles it. So the read is one decision, not two: pick the speed first, then the line that matches it. Best default for you: capture speed — pace that would finish about a foot past the hole — because it keeps the hole biggest and matches how you practice. The classic three-putt isn\'t a bad line, it\'s a line that never had a matching speed.',
    drill:'Same 12-foot breaker, three speeds: one that dies at the front edge, one a foot past, one two feet past. Watch how much line changes. Then hit three at capture speed on the capture-speed line — that pairing is the one to groove.' },
  { id:'g5', shelf:'Green Reading', title:'Find the fall line and short putts get simpler', min:3,
    tags:['short-putts','three-putts'],
    body:'Every hole has a fall line — the single straight-uphill path through the cup. Find it (picture where a ball dropped at the hole would roll off; that\'s straight downhill, and the fall line is its mirror) and every putt around the hole makes sense as a clock position: on the fall line, the putt is straight; the further you move around the clock toward 3 or 9 o\'clock, the more it breaks. Two payoffs: your read has a reference instead of a guess, and on approach and lag putts you can leave the ball below the hole on purpose — turning tomorrow\'s scary slider into a straight uphill tap-in.',
    drill:'Around-the-clock at 4 ft: find the fall line first, place 8 balls around the hole, and before each putt say its clock position and expected break out loud. This stacks straight onto your 10-ball 5-footer test.' },
  // ---------- WEDGES & SHORT GAME ----------
  { id:'w1', shelf:'Wedges & Short Game', title:'The clock system: three swings, nine numbers', min:5,
    tags:['wedge-distance','approach'],
    body:'Guessing at partial wedges is why you get stuck between clubs. Give each wedge three calibrated swings — feel them as a clock: hands to 9 o\'clock (half), 10:30 (three-quarter), and full. Three wedges × three swings = nine reliable carry numbers that cover everything from 45 to 110 yards. Fill the matrix in your Bag tab once at the range with 5 balls per swing, then trust it on the course.',
    drill:'Range session: 5 balls per swing length per wedge, note the average carry (ignore the best and worst). Enter the numbers in the wedge matrix. Re-check twice a season.' },
  { id:'w2', shelf:'Wedges & Short Game', title:'Bounce is your friend — especially yours', min:4,
    tags:['chipping','bunkers','equipment'],
    body:'Bounce is the sole angle that stops the leading edge digging. As a shallow sweeper you flirt with thin strikes when bounce sits too high — which is why your build runs mid bounce (10/10/8), not 12–14°. Around the greens, use the bounce: weight only slightly forward, hands level (not dramatically pressed), and let the sole slide under the ball. The blade only digs when hands get too far ahead and the leading edge is presented to the turf.',
    drill:'Brush drill: no ball, make chipping swings that brush the grass with the sole — listen for a "thump," not a scrape of the leading edge. Then hit 10 chips trying to reproduce that thump.' },
  { id:'w3', shelf:'Wedges & Short Game', title:'Chip vs. pitch: pick the boring one', min:3,
    tags:['chipping','approach'],
    body:'Default order around the green: putt if you can, chip-and-run if you can\'t putt, pitch only when you must carry something. A low runner with your 50° breaks less stuff than a floated 60° — more margin on strike, spin and landing spot. Save the 60° flop (your M-grind specialty) for short-sided lies where nothing else works. The best short-game players are the most boring ones.',
    drill:'One ball, three clubs: from the same greenside lie, play a 50° runner, a 56° standard, and a 60° pitch to the same pin. Note which finishes closest — nine times out of ten it\'s the lowest-lofted option that was available.' },
  { id:'w4', shelf:'Wedges & Short Game', title:'Distance control is landing-spot control', min:3,
    tags:['chipping','wedge-distance'],
    body:'Stop looking at the pin on chips — pick the exact spot where the ball should land, usually a few paces onto the green, and let the roll-out do the rest. Rough guide: a 50° runner rolls about 2× its carry, a 56° about 1×, a 60° about half. Land three different clubs on the same spot and you get three different finish distances — that\'s the whole short game in one sentence.',
    drill:'Towel drill: lay a towel 3 paces onto the green. 5 balls each with 50°, 56°, 60°, all landing on the towel. Watch how differently they finish.' },
  // ---------- COURSE MANAGEMENT ----------
  { id:'c1', shelf:'Course Management', title:'Tee shots: play to the fat side', min:4,
    tags:['off-tee'],
    body:'The driver question isn\'t "can I hit the fairway" — it\'s "where is the miss that ruins the hole." Before every tee shot, find the side where a miss is dead (water, OB, trees, bunkers you can\'t advance from) and aim so your normal shot pattern fits on the other side. An 8-handicap\'s dispersion is roughly 60 yards wide with driver; give that oval room. Sometimes that means the 5-wood or the 2-iron utility — those are your fairway finders now that the mini driver is out of the bag — and par is a fine score from the fairway. One honest gap while you use this: the 5-wood\'s carry is unmeasured, so on a hole where the number matters, the 2-iron is the one you actually have a figure for.',
    drill:'Next round: on every tee, say the dead side out loud before choosing a club and target. Log how many penalty strokes you take off the tee vs. your average.' },
  { id:'c2', shelf:'Course Management', title:'Approach shots: the pin is a lie', min:4,
    tags:['approach'],
    body:'At 8–9 handicap, aiming at tucked pins is a leak. Your proximity from 150 yards is 45+ feet on average — an aim point at the pin near an edge puts half your shots in the bunker or rough. Aim at the fat of the green (usually center, adjusted a touch toward the pin) and take the extra club: amateurs miss short far more than long. Center of green, back-edge distance, every time — birdies still happen, doubles stop happening.',
    drill:'One round experiment: aim dead center of every green regardless of pin. Count greens hit and compare to your average.' },
  { id:'c3', shelf:'Course Management', title:'Lay up to a full number', min:3,
    tags:['approach','wedge-distance'],
    body:'This is the single best-evidenced job in your whole game, so it is worth more than a rule of thumb. Two independent data sets say the same thing: three seasons of GHIN have your par-5 average getting worse every year without exception (5.46 → 5.72 → 5.88), and the Wianno member-guest produced ZERO birdies from eight par-5 plays. Different data, one conclusion. The mechanism is the lay-up. When you can\'t reach a par 5 or you must pitch out, don\'t just advance the ball — lay up to one of your CALIBRATED wedge numbers rather than to wherever a comfortable swing happens to finish. A full 95-yard 56° beats an awkward 60-yard half-something, because a full swing has one speed and a half swing has infinite. Know your favourite number and hit lay-ups to it on purpose.',
    drill:'Pick your money number (most players: full gap wedge). Next three rounds, every lay-up finishes at that number. Track proximity from it.' },
  { id:'c4', shelf:'Course Management', title:'Bogey is not an emergency', min:3,
    tags:['mental','off-tee'],
    body:'The difference between an 84 and a 79 isn\'t more birdies — it\'s fewer doubles, and your own cards put a number on it: across the hole-by-hole rounds on record, doubles and worse are about HALF of every stroke you have lost. Thirteen holes cost twenty-six shots. Doubles come from hero recoveries: the 3-wood from the trees, the flop over water off a tight lie. The rule that kills them is decided before you are angry — from any recovery position, pick the club and line you would bet a hundred dollars you can execute nine times in ten. From trouble that is nearly always the punch-out. When you are hot the club goes DOWN, never up. Count doubles per round in your log; driving that number toward zero is the fastest handicap drop available to you.',
    drill:'Trouble rule for one month: from any recovery spot, choose the club and line you would bet $100 you can execute 9 times out of 10. Nothing fancier.' },
  // ---------- MENTAL GAME ----------
  { id:'m1', shelf:'Mental Game', title:'One target, one thought', min:3,
    tags:['mental','approach','off-tee'],
    body:'Standing over the ball with three swing thoughts is a guarantee of a steer. The routine that works: pick the smallest possible target (not "the fairway" — a branch, a window, a mower line), one rehearsal feeling the shot, then swing with only the target in mind. Mechanics belong on the range; targets belong on the course.',
    drill:'Range game: never hit two balls at the same target. Every ball gets a new small target and a full routine. 20 balls = 20 first swings.' },
  { id:'m2', shelf:'Mental Game', title:'The 10-yard reset', min:3,
    tags:['mental'],
    body:'After a bad hole, the next tee shot is the most dangerous swing of the day — you\'re still replaying the double. Give yourself a hard reset ritual: after holing out, you get 10 yards of walking to be angry. At the 10-yard mark, the hole is filed away and the only thing that exists is the next shot. Sounds silly; works because it gives frustration a container instead of pretending it isn\'t there.',
    drill:'Practice it on good holes too: 10 yards of review, then present-tense only. The ritual has to be automatic before it\'s needed.' },
  { id:'m3', shelf:'Mental Game', title:'Practice like it counts', min:3,
    tags:['mental','short-putts'],
    body:'Twenty casual 5-footers teach you less than five with consequences. Pressure is a skill you can rehearse: put a score on everything, make yourself finish drills with a made putt, restart streaks when you miss. The 20-ball five-footer in your Putting Lab exists precisely for this — a number you can\'t talk your way out of, and the thing that decides every short-putt question instead of a feeling.',
    drill:'Finish every practice session with "3 to leave": three straight 5-footers with your full routine. Miss one, start over. You\'re not allowed to leave until it\'s done.' },
  // ---------- BUNKER PLAY ----------
  { id:'b1', shelf:'Bunker Play', title:'Hit the sand, not the ball', min:4,
    tags:['bunkers'],
    body:'The standard splash shot never touches the ball — the club enters the sand about two inches behind it and the sand throws the ball out. Setup does most of the work: face slightly open before you grip, ball forward of center, weight favoring the front foot, and swing along your body line with commitment. Your 56° with 10° of bounce is built for exactly this — let the sole skid, don\'t dig the leading edge.',
    drill:'Line drill: draw a line in the practice bunker, no ball. Make swings that splash sand starting at the line. Then put balls two inches ahead of the line and keep hitting the line.' },
  { id:'b2', shelf:'Bunker Play', title:'Bunker distance is follow-through length', min:3,
    tags:['bunkers'],
    body:'Same splash, different finishes: a short follow-through throws the ball a few paces; a full high finish sends it 20+ yards. Keep the entry point and effort identical and control distance only with how far the club swings through. Deceleration is the one unforgivable sin in sand — always finish.',
    drill:'Three-flag drill: pick short, middle and long targets from the same bunker. 5 balls each, changing nothing but follow-through length.' },
  { id:'b3', shelf:'Bunker Play', title:'Plugged lies: close the face, dig, walk away', min:3,
    tags:['bunkers'],
    body:'A fried-egg or plugged lie reverses the normal rules: square or slightly closed face, ball back of center, and a steep chop into the sand right behind the ball. The ball comes out low with no spin and runs — plan for that roll-out and just get it on the green. Trying to splash a plugged ball with an open face is how bunkers eat a whole scorecard.',
    drill:'Step on three balls in the practice bunker and play them out. Learning the shot when it doesn\'t count removes the panic when it does.' },
  // ---------- EQUIPMENT KNOWLEDGE ----------
  { id:'e1', shelf:'Equipment Knowledge', title:'Why a toe-hang putter fought your stroke', min:4,
    tags:['short-putts','equipment'],
    body:'The idea this whole project opened with, and it is now SETTLED — worth keeping so it does not get re-litigated. Toe-hang putters are balanced to swing on an arc: the face naturally opens and closes through the stroke. Your overhead-confirmed stroke is straight-back-straight-through, which never re-squares a rotating face, so the toe keeps closing and the ball starts left. That is why the app flags a MISMATCH on any toe-flow head against your stroke, and the Newport 2 in the bullpen is the last one you own. What is settled: you play a zero-torque L.A.B. head that holds the face square on its own, kept for good on Aug 12. What was NEVER equipment: the left miss survived three different putters, and on Aug 10 it was reclassified as an AIM error rather than a delivery one. So this explains a fault you already fixed with gear — it is not an argument that any remaining putting problem is buyable.',
    drill:'At the demo: 10 balls from 5 ft with the 7.5, then 10 with a zero-torque model, full routine both. The miss-direction pattern — not feel — makes the decision.' },
  { id:'e2', shelf:'Equipment Knowledge', title:'Grooves die quietly', min:3,
    tags:['equipment','wedge-distance','chipping'],
    body:'Wedge grooves wear down through sand, range balls and dirt — and spin loss is gradual, so you never notice the day it happens. By roughly 75–100 rounds a wedge can lose a third of its spin: chips release farther, full shots fly a touch longer and stop less. That\'s why the app counts rounds per wedge. Clean grooves after every shot from sand, and expect to replace your most-used wedge (the 56°) every couple of seasons.',
    drill:'Fingernail test: drag a nail across the face — grooves it doesn\'t catch in are worn. Compare the 56° face center vs. its unworn heel.' },
  { id:'e3', shelf:'Equipment Knowledge', title:'Grips: the 40-round rule', min:3,
    tags:['equipment'],
    body:'Grips harden and glaze long before they look worn. A slick grip forces a tighter hold, which adds tension all the way up to the shoulders — a swing killer nobody blames on the grip. Rule of thumb: regrip every 40 rounds or once a season, whichever comes first. The app counts your rounds so the reminder shows up before your grip pressure does.',
    drill:'Tension check: at address, hold the club at 3-out-of-10 grip pressure. If it feels like the club could slip, the grips are done.' },
  { id:'e4', shelf:'Equipment Knowledge', title:'Loft gaps beat brand loyalty', min:3,
    tags:['equipment','wedge-distance'],
    body:'The bag should be built around carry gaps, not logos. Your setup runs 44° PW then 50/56/60 — a 6/6/4 spread that plays fine off a strong PW. The sign it needs work: repeatedly finding yourself between clubs at the same yardage. If your logs show that, the fix is a 4-wedge ladder (48/52/56/60) at the cost of a long iron. Let the data in your rounds decide, not the shop wall.',
    drill:'For two weeks, note every approach where you were "between clubs" and the yardage. Three or more at the same number = a real gap.' },
];
