const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const root = path.join(__dirname, '..');
const dummy = { addEventListener(){}, querySelectorAll(){return []}, classList:{add(){},remove(){},toggle(){}}, style:{}, dataset:{} };
const ctx = { console, setTimeout(){}, clearTimeout(){}, setInterval(){}, document:{addEventListener(){},querySelector(){return dummy},querySelectorAll(){return []},getElementById(){return dummy},body:dummy}, navigator:{}, localStorage:{getItem(){return null},setItem(){}}, window:{addEventListener(){},matchMedia:()=>({matches:false,addEventListener(){}})} };
ctx.window.CaddieReview = require('../round-review.js');
vm.createContext(ctx);
for(const file of ['lessons.js','courses-db.js','course-cards.js']) vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),ctx);
let src = fs.readFileSync(path.join(root,'app.js'),'utf8');
src = src.slice(0,src.indexOf('// ---------- Boot ----------')) + '\nrerender=()=>{};toast=()=>{};load();window.apexTest={analysisClubs,bayClubTable,rangeShotTables,applyFeed,get:()=>S};})();';
vm.runInContext(src,ctx);
const {analysisClubs,bayClubTable,rangeShotTables,applyFeed,get} = ctx.window.apexTest;
const detail = {rangeShots:[
  {club:'5-iron',shots:[{shot:1,carry:170,height:"70'6\""},{shot:2,carry:175,height:"71'6\""},{shot:3,carry:168,height:null}]},
  {club:'5-wood',shots:[{shot:1,carry:180},{shot:2,carry:185}]}
]};
const clubs = analysisClubs(detail);
assert.equal(clubs[0].apex,71);
assert.equal(clubs[0].metricCounts.apex,2);
assert.equal(clubs[1].apex,null);
const table = bayClubTable(clubs);
assert.match(table,/APEX FT/);
assert.match(table,/71\.0 <small>n=2<\/small>/);
assert.match(rangeShotTables(detail),/70&#39;6&quot;|70'6&quot;/);
const feed = require('../range-20260922-feed.json');
const base = {updated:feed.updated,entries:[feed.entries[0]]};
const heights = {updated:feed.updated,entries:[feed.entries[1]]};
applyFeed(heights);
assert.ok(!get().feedApplied.includes(feed.entries[1].id),'correction retries if the day has not arrived');
applyFeed(base);
applyFeed(heights);
applyFeed(heights);
const day = get().bays.find(b=>b._fid===feed.entries[0].id);
const w3 = day.detail.rangeShots.find(g=>g.club==='3-wood');
const w5 = day.detail.rangeShots.find(g=>g.club==='5-wood');
assert.deepEqual(w3.shots.map(s=>s.height),["31'","44'10\"","41'11\"","32'4\"","29'9\"","33'8\"","63'11\""]);
assert.deepEqual(w5.shots.map(s=>[s.shot,s.height||null]),[[1,"56'11\""],[2,"17'6\""],[4,"51'4\""],[6,"57'10\""],[7,"37'7\""],[10,null],[11,null],[12,null]]);
assert.equal(w5.shots.find(s=>s.shot===10).carry,112.6,'mishit preserved as source but held from live data');
const woodRows=analysisClubs(day.detail).filter(c=>/wood/.test(c.club));
assert.equal(woodRows[0].apex,39.6);
assert.equal(woodRows[0].metricCounts.apex,7);
assert.equal(woodRows[1].apex,44.2);
assert.equal(woodRows[1].metricCounts.apex,5);
assert.match(bayClubTable(woodRows),/44\.2 <small>n=5<\/small>/);
const shotTable=rangeShotTables(day.detail);
assert.match(shotTable,/63&#39;11&quot;|63'11&quot;/);
assert.doesNotMatch(shotTable,/112\.6/,'held mishit absent from live exact shot table');
console.log('PASS: measured apex appears in exact club data with coverage; unmeasured apex stays blank.');
