const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const R=require('../round-review.js');
const entry=require('../data/ballybunion-2026-09-15.json');
const feed=JSON.parse(fs.readFileSync(path.join(__dirname,'../coach-feed.json'),'utf8'));
const r=entry.round;
assert.equal(r.holes.length,18);
assert.equal(r.holes.reduce((a,h)=>a+h.s,0),88);
assert.equal(r.holes.reduce((a,h)=>a+h.par,0),71);
assert.equal(new Set(r.review.shots.map(s=>s.id)).size,59);
assert.equal(r.review.shots.length,r.score-r.putts);
assert.equal(new Set(r.review.shots.map(s=>s.hole)).size,18);
assert.equal(feed.entries.filter(e=>e.id===entry.id).length,1);
const combined=structuredClone(feed.entries.find(e=>e.id===entry.id));
feed.entries.filter(e=>e.type==='round-review-update').forEach(e=>Object.assign(combined.round.review,e.review));
assert.deepEqual(combined,entry);
assert.equal(R.profiles(r,[]).length,6);
assert.deepEqual(Object.fromEntries(R.profiles(r,[]).map(p=>[p.club,p.n])),
  {driver:10,'mini-driver':9,'5-wood':5,'6-iron':4,'9-iron':3,'56-wedge':3});
const rr=structuredClone(r);rr.review.shots[0].actualClub='5-wood';rr.review.shots[0].intent='full';
assert.equal(R.profiles(rr,[]).find(p=>p.club==='5-wood').n,6);
rr.review.shots[0].flag='unreliable';
assert.equal(R.profiles(rr,[]).find(p=>p.club==='5-wood').n,5);
const bays=feed.entries.filter(e=>e.type==='bay').map(e=>({...e.bay,_fid:e.id}));
assert.equal(R.profiles(r,bays).find(p=>p.club==='driver').bay.carry,195.8);
assert.equal(R.profiles(r,bays).find(p=>p.club==='mini-driver').bay,undefined);
assert.equal(R.render({sim:false,review:{}},{}),'');
assert.doesNotThrow(()=>R.findings({}));
const unsafe=structuredClone(r);unsafe.review.shots[0].source='<script>alert(1)</script>';
assert.ok(!R.render(unsafe,{rounds:[],bays:[]}).includes('<script>'));
assert.equal(R.findings(r)[0].holes.length,5);
console.log('PASS: 18-hole totals, all 59 counted non-putting shots, all holes, feed integrity, six actual clubs, intent/flag exclusions, bay mapping, escaping and empty data.');
