const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const R=require('../round-review.js');
const entry=require('../data/ballybunion-2026-09-15.json');
const feed=JSON.parse(fs.readFileSync(path.join(__dirname,'../coach-feed.json'),'utf8'));
const r=entry.round;
assert.equal(r.holes.length,18);
assert.equal(r.holes.reduce((a,h)=>a+h.s,0),88);
assert.equal(r.holes.reduce((a,h)=>a+h.par,0),71);
assert.equal(new Set(r.review.shots.map(s=>s.id)).size,38);
assert.equal(new Set(r.review.shots.map(s=>s.hole)).size,18);
assert.equal(feed.entries.filter(e=>e.id===entry.id).length,1);
assert.deepEqual(feed.entries.find(e=>e.id===entry.id),entry);
assert.equal(R.profiles(r,[]).length,6);
assert.ok(R.profiles(r,[]).every(p=>p.n===0));
const rr=structuredClone(r);rr.review.shots[0].actualClub='5-wood';rr.review.shots[0].intent='full';
assert.equal(R.profiles(rr,[]).find(p=>p.club==='5-wood').n,1);
rr.review.shots[0].flag='unreliable';
assert.equal(R.profiles(rr,[]).find(p=>p.club==='5-wood').n,0);
const bays=feed.entries.filter(e=>e.type==='bay').map(e=>({...e.bay,_fid:e.id}));
assert.equal(R.profiles(r,bays).find(p=>p.club==='driver').bay.carry,195.8);
assert.equal(R.profiles(r,bays).find(p=>p.club==='mini-driver').bay,undefined);
assert.equal(R.render({sim:false,review:{}},{}),'');
assert.doesNotThrow(()=>R.findings({}));
const unsafe=structuredClone(r);unsafe.review.shots[0].source='<script>alert(1)</script>';
assert.ok(!R.render(unsafe,{rounds:[],bays:[]}).includes('<script>'));
assert.equal(R.findings(r)[0].holes.length,5);
console.log('PASS: 18-hole totals, 38 unique observations, all holes, feed integrity, six actual clubs, uncertain/flagged exclusions, bay mapping, escaping and empty data.');
