const vm=require('node:vm'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.join(__dirname,'..');
const dummy={addEventListener(){},querySelectorAll(){return []},classList:{add(){},remove(){},toggle(){}},style:{},dataset:{}};
const ctx={console,setTimeout(){},clearTimeout(){},setInterval(){},document:{addEventListener(){},querySelector(){return dummy},querySelectorAll(){return []},getElementById(){return dummy},body:dummy},navigator:{},localStorage:{getItem:()=>null,setItem(){}},window:{addEventListener(){},matchMedia:()=>({matches:false,addEventListener(){}})}};
ctx.window.CaddieReview=require('../round-review.js');vm.createContext(ctx);
for(const f of ['lessons.js','courses-db.js','course-cards.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),ctx);
let src=fs.readFileSync(path.join(root,'app.js'),'utf8');src=src.slice(0,src.indexOf('// ---------- Boot ----------'))+`rerender=()=>{};toast=()=>{};load();window.T={applyFeed,get:()=>S,realRounds,roundView};})();`;vm.runInContext(src,ctx);const T=ctx.window.T;
const read=f=>JSON.parse(fs.readFileSync(path.join(root,f),'utf8'));
T.applyFeed(read('coach-feed.json'));
const baseline=JSON.stringify(T.realRounds()),carries=JSON.stringify(T.get().carries);
const fixes=read('corrections-20260922.json');T.applyFeed(fixes);T.applyFeed(fixes);
const haz=T.get().rounds.find(r=>r.feedId==='round-tm-hazeltine-imported-v1');
assert.equal(haz.sim,true);assert.equal(haz.score,80);assert.equal(haz.holes.length,18);
assert.equal(haz.holes.reduce((s,h)=>s+h.s,0),80);
assert.equal(haz.holes.slice(0,9).reduce((s,h)=>s+h.s,0),41);
assert.equal(haz.holes.slice(9).reduce((s,h)=>s+h.s,0),39);
assert.deepEqual(Array.from(haz.holes,h=>h.s),[5,3,6,3,5,5,5,4,5,5,5,4,4,5,6,4,2,4]);
assert.ok(haz.review.shots.some(s=>s.hole===6&&s.spin===1958&&s.carry===191.6));
for(const [hole,club,distance] of [[7,'56-wedge',40],[10,'5-iron',116],[13,'5-iron',67]])
 assert.ok(!haz.review.shots.some(s=>s.hole===hole&&s.club===club&&s.distance===distance),'canceled mulligan excluded');
assert.equal(haz.putts,null,'do not synthesize putts from partial shot evidence');
assert.equal(JSON.stringify(T.realRounds()),baseline);assert.equal(JSON.stringify(T.get().carries),carries);
assert.equal(T.get().rounds.filter(r=>r.feedId===haz.feedId).length,1);
assert.ok(T.roundView(T.get().rounds.indexOf(haz)).includes('front 41 / back 39'));
console.log('PASS filmed round corrections: 18 Hazeltine scores, verified panels, excluded mulligans, repeat imports and outdoor isolation.');

const spy=T.get().rounds.find(r=>r.feedId==='round-tm-spyglass-20260915-review-v1');
assert.equal(spy.score,85);assert.equal(spy.putts,28);assert.equal(spy.review.shots.length,57);
assert.equal(spy.review.shots.length+spy.putts,spy.score);
assert.equal(spy.holes.reduce((n,h)=>n+h.putts,0),28);
assert.equal(spy.review.shots.find(s=>s.id==='h3-a').carry,129.6);
assert.equal(spy.review.shots.find(s=>s.id==='h5-a').club,'5-iron');
assert.ok(!spy.review.shots.some(s=>s.id==='h7-c'));
assert.equal(spy.review.shots.filter(s=>s.hole===7).length,4);
assert.equal(spy.review.shots.filter(s=>s.hole===10).length,4);
assert.equal(spy.review.shots.filter(s=>s.flag).length,2);
for(const s of spy.review.shots.filter(s=>s.flag)) assert.equal(s.carry,undefined,'unreadable carry is not invented');
assert.ok(spy.review.shots.every(s=>s.source.includes('ScreenRecording_09-22-2026')));
console.log('PASS Spyglass source repair:57 counted shots +28 assigned putts, missing rows restored, unsupported row removed, uncertain metrics blank.');
